"""Tests for hash_message parity with JS implementation.

Fixtures generated by running the JS hashMessage() from gt-i18n and
saved in fixtures/js_parity.json.
"""

import json
from pathlib import Path
from typing import Any

import pytest
from generaltranslation.static._index_vars import index_vars
from gt_i18n.translation_functions._hash_message import hash_message

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "js_parity.json"


@pytest.fixture(scope="module")
def fixtures() -> dict[str, Any]:
    return json.loads(FIXTURES_PATH.read_text())


# ---- indexVars parity ----


class TestIndexVarsParity:
    """Verify index_vars produces identical output to JS indexVars."""

    @pytest.fixture(autouse=True)
    def _load(self, fixtures: dict[str, Any]) -> None:
        self.cases = fixtures["indexVars"]

    def test_plain_no_vars(self) -> None:
        c = self.cases["plain_no_vars"]
        assert index_vars(c["input"]) == c["output"]

    def test_simple_variable(self) -> None:
        c = self.cases["simple_variable"]
        assert index_vars(c["input"]) == c["output"]

    def test_single_gt(self) -> None:
        c = self.cases["single_gt"]
        assert index_vars(c["input"]) == c["output"]

    def test_two_gt(self) -> None:
        c = self.cases["two_gt"]
        assert index_vars(c["input"]) == c["output"]

    def test_gt_with_var_name(self) -> None:
        c = self.cases["gt_with_var_name"]
        assert index_vars(c["input"]) == c["output"]

    def test_nested_in_plural(self) -> None:
        c = self.cases["nested_in_plural"]
        assert index_vars(c["input"]) == c["output"]

    def test_empty_string(self) -> None:
        c = self.cases["empty_string"]
        assert index_vars(c["input"]) == c["output"]

    def test_no_placeholders(self) -> None:
        c = self.cases["no_placeholders"]
        assert index_vars(c["input"]) == c["output"]


# ---- hashMessage parity ----


def _js_options_to_kwargs(options: dict) -> dict:
    """Convert JS-style options (camelCase) to Python kwargs (snake_case)."""
    kwargs = {}
    if "context" in options:
        kwargs["context"] = options["context"]
    if "id" in options:
        kwargs["id"] = options["id"]
    if "maxChars" in options:
        kwargs["max_chars"] = options["maxChars"]
    return kwargs


class TestHashMessageParity:
    """Verify hash_message produces identical hashes to JS hashMessage."""

    @pytest.fixture(autouse=True)
    def _load(self, fixtures: dict[str, Any]) -> None:
        self.cases = fixtures["hashMessage"]

    def test_plain(self) -> None:
        c = self.cases["plain"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_variable(self) -> None:
        c = self.cases["with_variable"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_context_button(self) -> None:
        c = self.cases["with_context_button"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_context_menu(self) -> None:
        c = self.cases["with_context_menu"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_no_context(self) -> None:
        c = self.cases["no_context"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_id(self) -> None:
        c = self.cases["with_id"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_max_chars(self) -> None:
        c = self.cases["with_max_chars"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_negative_max_chars_same_as_positive(self) -> None:
        """maxChars(-10) should produce the same hash as maxChars(10)."""
        c = self.cases["with_negative_max_chars"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]
        # Also verify it equals the positive case
        pos = self.cases["with_max_chars"]
        assert c["hash"] == pos["hash"]

    def test_empty(self) -> None:
        c = self.cases["empty"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_plural(self) -> None:
        c = self.cases["plural"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_plural_sentence(self) -> None:
        c = self.cases["plural_sentence"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_gt_var(self) -> None:
        c = self.cases["with_gt_var"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_with_gt_var_name(self) -> None:
        c = self.cases["with_gt_var_name"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_context_and_id(self) -> None:
        c = self.cases["context_and_id"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]

    def test_context_and_max_chars(self) -> None:
        c = self.cases["context_and_max_chars"]
        assert hash_message(c["message"], **_js_options_to_kwargs(c["options"])) == c["hash"]


# ---- Behavioral tests ----


def test_same_message_same_hash() -> None:
    h1 = hash_message("Hello, world!")
    h2 = hash_message("Hello, world!")
    assert h1 == h2


def test_different_messages_different_hash() -> None:
    h1 = hash_message("Hello")
    h2 = hash_message("Goodbye")
    assert h1 != h2


def test_context_changes_hash() -> None:
    h1 = hash_message("Save", context="button")
    h2 = hash_message("Save", context="menu")
    h3 = hash_message("Save")
    assert h1 != h2
    assert h1 != h3


def test_with_declare_var() -> None:
    from generaltranslation.static._declare_var import declare_var

    msg = f"Hello, {declare_var('Alice', name='user')}!"
    h = hash_message(msg)
    assert isinstance(h, str)
    assert len(h) == 16
