"""Bulk hash-parity tests: Python ``hash_message`` must match the JS ``hashMessage``.

Fixtures are generated by ``generate_runtime_fixtures.mjs`` against the JS
monorepo at ``~/Documents/dev/gt`` and committed as
``fixtures/runtime_translation_parity.json`` (1040 (message, format, ...) cases).

Each fixture case becomes one parametrized test. Parametrize IDs embed the
format and index so a failure points at a specific entry:

    test_hash_parity[ICU-13]         → 14th ICU case
    test_hash_parity[STRING-7]       → 8th STRING case
    test_hash_parity[I18NEXT-22]     → 23rd I18NEXT case

If a single case fails, the Python ``hash_message`` has drifted from the JS
reference for that combination of (message, format, context, id, maxChars).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from gt_i18n.translation_functions._hash_message import hash_message

FIXTURES_PATH = Path(__file__).parent.parent / "fixtures" / "runtime_translation_parity.json"


def _load_fixtures() -> dict[str, Any]:
    return json.loads(FIXTURES_PATH.read_text())


def _indexed_cases() -> list[tuple[str, dict[str, Any]]]:
    """Yield (test_id, case) pairs keyed by ``{format}-{index-within-format}``."""
    data = _load_fixtures()
    counters: dict[str, int] = {}
    out: list[tuple[str, dict[str, Any]]] = []
    for case in data["cases"]:
        fmt = case["format"]
        idx = counters.get(fmt, 0)
        counters[fmt] = idx + 1
        out.append((f"{fmt}-{idx}", case))
    return out


INDEXED_CASES = _indexed_cases()
CASE_IDS = [cid for cid, _ in INDEXED_CASES]
CASES = [c for _, c in INDEXED_CASES]


# ---------------------------------------------------------------------------
# Bulk parity — one test per fixture case
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", CASES, ids=CASE_IDS)
def test_hash_parity(case: dict[str, Any]) -> None:
    """Python ``hash_message`` matches JS ``hashMessage`` for this specific case."""
    kwargs: dict[str, Any] = {"format": case["format"]}
    if case["context"] is not None:
        kwargs["context"] = case["context"]
    if case["id"] is not None:
        kwargs["id"] = case["id"]
    if case["maxChars"] is not None:
        kwargs["max_chars"] = case["maxChars"]

    got = hash_message(case["message"], **kwargs)
    assert got == case["hash"], (
        f"Hash mismatch for format={case['format']} message={case['message']!r} "
        f"context={case['context']!r} id={case['id']!r} maxChars={case['maxChars']!r}\n"
        f"  expected (JS): {case['hash']}\n  got    (Python): {got}"
    )


# ---------------------------------------------------------------------------
# Cross-format collision tests — same message hashed as ICU vs STRING vs I18NEXT
# must produce three DIFFERENT hashes (except empty message where ICU == STRING
# since indexVars of empty is empty).
# ---------------------------------------------------------------------------


def _collision_cases() -> list[dict[str, Any]]:
    data = _load_fixtures()
    return data["collisionCases"]


def _collision_ids() -> list[str]:
    cases = _collision_cases()
    out = []
    for i, c in enumerate(cases):
        msg_repr = c["message"][:20].replace(" ", "_") or "empty"
        ctx = c["context"] or "none"
        out.append(f"{i}-{msg_repr}-ctx={ctx}")
    return out


@pytest.mark.parametrize("case", _collision_cases(), ids=_collision_ids())
def test_cross_format_collision(case: dict[str, Any]) -> None:
    """All three format hashes for a given (message, context) are mutually distinct in Python.

    The only exception is very short messages that happen to produce the same
    bytes after normalization — the JS fixture already reflects these collisions,
    so we assert parity against the JS output rather than strict distinctness.
    """
    message = case["message"]
    context = case["context"]
    kwargs: dict[str, Any] = {}
    if context is not None:
        kwargs["context"] = context

    py_hashes = {fmt: hash_message(message, format=fmt, **kwargs) for fmt in ("ICU", "STRING", "I18NEXT")}
    assert py_hashes == case["hashes"], (
        f"Collision-set mismatch for message={message!r} context={context!r}\n"
        f"  expected (JS): {case['hashes']}\n  got    (Python): {py_hashes}"
    )


# ---------------------------------------------------------------------------
# Sanity: every fixture case has a well-formed (16-char hex) hash.
# Catches fixture corruption early.
# ---------------------------------------------------------------------------


def test_fixture_hashes_are_well_formed() -> None:
    """Every fixture case's hash is a 16-character hex string."""
    data = _load_fixtures()
    bad = [c for c in data["cases"] if not (isinstance(c["hash"], str) and len(c["hash"]) == 16)]
    assert not bad, f"{len(bad)} malformed hashes in fixture; first: {bad[0] if bad else None}"


def test_fixture_has_expected_volume() -> None:
    """Fixture contains enough cases to actually stress the implementation."""
    data = _load_fixtures()
    assert data["caseCount"] >= 500, f"fixture should have >= 500 cases; got {data['caseCount']}"
    formats = {c["format"] for c in data["cases"]}
    assert formats == {"ICU", "STRING", "I18NEXT"}


def test_fixture_covers_all_three_formats_with_all_option_variants() -> None:
    """Each format has at least one case with each option combination present."""
    data = _load_fixtures()
    for fmt in ("ICU", "STRING", "I18NEXT"):
        fmt_cases = [c for c in data["cases"] if c["format"] == fmt]
        assert any(c["context"] is not None for c in fmt_cases), f"no {fmt} cases with context"
        assert any(c["id"] is not None for c in fmt_cases), f"no {fmt} cases with id"
        assert any(c["maxChars"] is not None for c in fmt_cases), f"no {fmt} cases with maxChars"
        assert any(c["context"] is None and c["id"] is None and c["maxChars"] is None for c in fmt_cases), (
            f"no {fmt} cases with all options None"
        )
